language: elixir
elixir:
  - 1.10

otp_release:
  - 22

addons:
  postgres: '9.4'

services:
  - postgresql

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobellow --config
  - mix coveralls.travis
